import logging
import datetime
from typing import Dict, List
from src.models.schemas import CritiqueReport, Paper
from src.utils.llm import load_prompt, call_aimlabs

logger = logging.getLogger("ResearchPilot.WriterAgent")

class WriterAgent:
    """Agent responsible for compiling the structured research review from draft segments."""
    
    def __init__(self):
        self.system_instruction_template = load_prompt("writer")
        
    def run(self, query: str, syntheses: Dict[str, str], critiques: Dict[str, CritiqueReport], papers_by_subq: Dict[str, List[Paper]]) -> str:
        """
        Assembles and edits the drafts into a publication-ready literature review report.
        """
        logger.info(f"WriterAgent compiling final report for query: '{query}'")
        
        # 1. Format date
        today_str = datetime.date.today().strftime("%B %d, %Y")
        
        # 2. Build detailed sections block for LLM context (including paper URLs for citations)
        sections_data = ""
        for i, sub_q in enumerate(syntheses.keys(), 1):
            synthesis_text = syntheses[sub_q]
            critique = critiques.get(sub_q)
            papers = papers_by_subq.get(sub_q, [])
            
            coverage = critique.coverage if critique else 0
            grounding = critique.grounding if critique else 0
            citations = critique.citations if critique else 0
            revision_notes = critique.revision_notes if critique else ""
            
            # Build sources list with links
            sources_text = ""
            if papers:
                sources_text = "\nAvailable Sources:\n"
                for p in papers:
                    url = p.external_url or f"https://arxiv.org/abs/{p.id.replace('arxiv_', '')}"
                    sources_text += f"- {p.title} — {', '.join(p.authors[:3])}{' et al.' if len(p.authors) > 3 else ''} ({p.year}) — {url}\n"
            
            sections_data += (
                f"--- SECTION {i} ---\n"
                f"Sub-question: {sub_q}\n"
                f"Synthesis Draft:\n{synthesis_text}\n"
                f"{sources_text}"
                f"Quality Scores: Coverage {coverage}/10 | Grounding {grounding}/10 | Citations {citations}/10\n"
                f"Reviewer Notes: {revision_notes}\n\n"
            )
            
        system_instruction = (
            self.system_instruction_template
            .replace("{query}", query)
            .replace("{date}", today_str)
            .replace("{num_sub_questions}", str(len(syntheses)))
        )
        
        prompt = (
            f"Original Query: {query}\n"
            f"Date: {today_str}\n\n"
            f"Section Drafts and Scores:\n"
            f"{sections_data}\n\n"
            f"Please generate the complete, cohesive, and cited Markdown document with a 'Sources' subsection under each sub-question containing the clickable links."
        )
        
        # 4. Call LLM
        try:
            final_report = call_aimlabs(
                system_instruction=system_instruction,
                prompt=prompt,
                json_mode=False
            )
            logger.info("Successfully compiled final literature review.")
            return final_report
        except Exception as e:
            logger.error(f"Error compiling final report: {str(e)}")
            return (
                f"# Literature Review: {query}\n"
                f"Generated by ResearchPilot | Date: {today_str}\n\n"
                f"Error: The Writer Agent failed to compile the complete report due to an LLM error.\n"
            )
