from typing import List, Dict, Optional
from pydantic import BaseModel, Field

class Paper(BaseModel):
    """Represents a retrieved academic paper and its metadata."""
    id: str = Field(..., description="Unique paper identifier, e.g., 'arxiv_1234' or 'semantic_scholar_5678'")
    title: str = Field(..., description="Title of the paper")
    authors: List[str] = Field(default_factory=list, description="List of paper authors")
    year: Optional[int] = Field(None, description="Publication year")
    abstract: str = Field("", description="Paper abstract text")
    source: str = Field(..., description="Source API of the paper: 'arxiv' or 'semantic_scholar'")
    citation_count: int = Field(0, description="Citation count from Semantic Scholar")
    external_url: Optional[str] = Field(None, description="URL to the paper source page or PDF")

class CritiqueReport(BaseModel):
    """Quality critique generated by the Critic agent for a synthesis draft."""
    coverage: int = Field(..., ge=0, le=10, description="Coverage score of the synthesis against sub-question (0-10)")
    grounding: int = Field(..., ge=0, le=10, description="Factual grounding score against source papers (0-10)")
    citations: int = Field(..., ge=0, le=10, description="Citation accuracy score (0-10)")
    revision_notes: str = Field("", description="Feedback and revision guidance if scores are below threshold")

class SessionState(BaseModel):
    """The orchestrator working memory representing current execution state."""
    query: str = Field(..., description="The original user query")
    sub_questions: List[str] = Field(default_factory=list, description="Decomposed research sub-questions")
    retrieved_papers: Dict[str, List[Paper]] = Field(
        default_factory=dict, 
        description="Mapping from sub-question to list of relevant retrieved papers"
    )
    synthesis_drafts: Dict[str, str] = Field(
        default_factory=dict, 
        description="Mapping from sub-question to generated draft synthesis"
    )
    critiques: Dict[str, CritiqueReport] = Field(
        default_factory=dict, 
        description="Mapping from sub-question to Critic agent reports"
    )
    final_report: str = Field("", description="The final compiled literature review report")
